-- MySQL Script generated by MySQL Workbench
-- Mon Sep 17 15:14:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema practicum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema practicum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `practicum` ;
USE `practicum` ;

-- -----------------------------------------------------
-- Table `practicum`.`sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicum`.`sexo` (
  `id_sexo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`id_sexo`),
  UNIQUE INDEX `id_sexo_UNIQUE` (`id_sexo` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practicum`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicum`.`educacion` (
  `id_educacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`id_educacion`),
  UNIQUE INDEX `id_educacion_UNIQUE` (`id_educacion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practicum`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicum`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `carreras` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(400) NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practicum`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicum`.`horario` (
  `id_horario` INT NOT NULL AUTO_INCREMENT,
  `tipo` TIME NOT NULL,
  PRIMARY KEY (`id_horario`),
  UNIQUE INDEX `id_horario_UNIQUE` (`id_horario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practicum`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicum`.`localidad` (
  `id_localidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(22) NOT NULL,
  PRIMARY KEY (`id_localidad`),
  UNIQUE INDEX `id_localidad_UNIQUE` (`id_localidad` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practicum`.`ingles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicum`.`ingles` (
  `id_nivel` INT NOT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_nivel`),
  UNIQUE INDEX `id_nivel_UNIQUE` (`id_nivel` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practicum`.`user_register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicum`.`user_register` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(50) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC));


-- -----------------------------------------------------
-- Table `practicum`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicum`.`usuario` (
  `user_register_id_usuario` INT NOT NULL,
  `nombre` VARCHAR(12) NULL,
  `apellido_paterno` VARCHAR(22) NULL,
  `apellido_materno` VARCHAR(22) NULL,
  `edad` INT NULL,
  `telefono` VARCHAR(15) NULL,
  `celular` VARCHAR(15) NULL,
  `linkedin` VARCHAR(50) NULL,
  `semestres_expe` INT NULL,
  `sueldo_deseado` INT NULL,
  `sueldo_actual` INT NULL,
  `fecha_registro` TIMESTAMP NULL,
  `sexo_id_sexo` INT NULL,
  `educacion_id_educacion` INT NULL,
  `categoria_id_categoria` INT NULL,
  `horario_id_horario` INT NULL,
  `localidad_id_localidad` INT NULL,
  `descripcion_habilidad` VARCHAR(450) NULL,
  `ingles_id_nivel` INT NULL,
  `activo` TINYINT(1) NOT NULL,
  `completo` TINYINT(1) NOT NULL,
  `descripcion_persona` VARCHAR(45) NULL,
  UNIQUE INDEX `linkedin_UNIQUE` (`linkedin` ASC),
  INDEX `fk_usuario_sexo_idx` (`sexo_id_sexo` ASC),
  INDEX `fk_usuario_educacion1_idx` (`educacion_id_educacion` ASC),
  INDEX `fk_usuario_categoria1_idx` (`categoria_id_categoria` ASC),
  INDEX `fk_usuario_horario1_idx` (`horario_id_horario` ASC),
  INDEX `fk_usuario_localidad1_idx` (`localidad_id_localidad` ASC),
  INDEX `fk_usuario_ingles1_idx` (`ingles_id_nivel` ASC),
  PRIMARY KEY (`user_register_id_usuario`),
  UNIQUE INDEX `user_register_id_usuario_UNIQUE` (`user_register_id_usuario` ASC),
  CONSTRAINT `fk_usuario_sexo`
    FOREIGN KEY (`sexo_id_sexo`)
    REFERENCES `practicum`.`sexo` (`id_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_educacion1`
    FOREIGN KEY (`educacion_id_educacion`)
    REFERENCES `practicum`.`educacion` (`id_educacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_categoria1`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `practicum`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_horario1`
    FOREIGN KEY (`horario_id_horario`)
    REFERENCES `practicum`.`horario` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_localidad1`
    FOREIGN KEY (`localidad_id_localidad`)
    REFERENCES `practicum`.`localidad` (`id_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_ingles1`
    FOREIGN KEY (`ingles_id_nivel`)
    REFERENCES `practicum`.`ingles` (`id_nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_user_register1`
    FOREIGN KEY (`user_register_id_usuario`)
    REFERENCES `practicum`.`user_register` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practicum`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicum`.`subcategoria` (
  `id_subcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `categoria_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_subcategoria`),
  INDEX `fk_subcategoria_categoria1_idx` (`categoria_id_categoria` ASC),
  UNIQUE INDEX `id_subcategoria_UNIQUE` (`id_subcategoria` ASC),
  CONSTRAINT `fk_subcategoria_categoria1`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `practicum`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practicum`.`Competencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicum`.`Competencia` (
  `id_conocimientos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `subcategoria_id_subcategoria` INT NOT NULL,
  PRIMARY KEY (`id_conocimientos`),
  UNIQUE INDEX `id_conocimientos_UNIQUE` (`id_conocimientos` ASC),
  INDEX `fk_Competencia_subcategoria1_idx` (`subcategoria_id_subcategoria` ASC),
  CONSTRAINT `fk_Competencia_subcategoria1`
    FOREIGN KEY (`subcategoria_id_subcategoria`)
    REFERENCES `practicum`.`subcategoria` (`id_subcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practicum`.`tecnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicum`.`tecnica` (
  `id_ct` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `Competencia_id_conocimientos` INT NOT NULL,
  `pericidad` INT NULL,
  PRIMARY KEY (`id_ct`),
  UNIQUE INDEX `id_habilidad_UNIQUE` (`id_ct` ASC),
  INDEX `fk_tecnica_Competencia1_idx` (`Competencia_id_conocimientos` ASC),
  CONSTRAINT `fk_tecnica_Competencia1`
    FOREIGN KEY (`Competencia_id_conocimientos`)
    REFERENCES `practicum`.`Competencia` (`id_conocimientos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practicum`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicum`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `descripcion` VARCHAR(400) NULL,
  `correo` VARCHAR(55) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id_empresa`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_empresa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practicum`.`trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicum`.`trabajo` (
  `id_trabajo` INT NOT NULL AUTO_INCREMENT,
  `id_empresa` INT NOT NULL,
  `anos_exp` INT NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `salario` INT NOT NULL,
  `fecha_post` DATE NOT NULL,
  `categoria_id_categoria` INT NOT NULL,
  `educacion_id_educacion` INT NOT NULL,
  `localidad_id_localidad` INT NOT NULL,
  `sexo_id_sexo` INT NOT NULL,
  `ingles_id_nivel` INT NOT NULL,
  `descripcion` VARCHAR(800) NULL,
  `telefono` VARCHAR(20) NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_trabajo`),
  UNIQUE INDEX `id_trabajo_UNIQUE` (`id_trabajo` ASC),
  INDEX `fk_trabajo_categoria1_idx` (`categoria_id_categoria` ASC),
  INDEX `fk_trabajo_educacion1_idx` (`educacion_id_educacion` ASC),
  INDEX `fk_trabajo_localidad1_idx` (`localidad_id_localidad` ASC),
  INDEX `fk_trabajo_sexo1_idx` (`sexo_id_sexo` ASC),
  INDEX `fk_trabajo_ingles1_idx` (`ingles_id_nivel` ASC),
  INDEX `fk_trabajo_empresa1_idx` (`id_empresa` ASC),
  CONSTRAINT `fk_trabajo_categoria1`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `practicum`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabajo_educacion1`
    FOREIGN KEY (`educacion_id_educacion`)
    REFERENCES `practicum`.`educacion` (`id_educacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabajo_localidad1`
    FOREIGN KEY (`localidad_id_localidad`)
    REFERENCES `practicum`.`localidad` (`id_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabajo_sexo1`
    FOREIGN KEY (`sexo_id_sexo`)
    REFERENCES `practicum`.`sexo` (`id_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabajo_ingles1`
    FOREIGN KEY (`ingles_id_nivel`)
    REFERENCES `practicum`.`ingles` (`id_nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabajo_empresa1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `practicum`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practicum`.`admin_register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicum`.`admin_register` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(50) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_usuario`));


-- -----------------------------------------------------
-- Table `practicum`.`Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicum`.`Registro` (
  `id_registro` INT NOT NULL AUTO_INCREMENT,
  `fecha_` TIMESTAMP NULL,
  `trabajo_id_trabajo` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_registro`),
  UNIQUE INDEX `id_registro_UNIQUE` (`id_registro` ASC),
  INDEX `fk_Registro_trabajo1_idx` (`trabajo_id_trabajo` ASC),
  CONSTRAINT `fk_Registro_trabajo1`
    FOREIGN KEY (`trabajo_id_trabajo`)
    REFERENCES `practicum`.`trabajo` (`id_trabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
